spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1d-u65z2n58k5x48jw0.mdb.yandexcloud.net:6432/chomik-payment
    username: chomik
    password: ${DB_PASSWORD}

payment:
  mock:
    url: http://payment-mock:17006

chomik:
  order:
    url: http://chomik-orders-balancer:80
  bank:
    account:
      id: {BANK_ACCOUNT_ID}

gateway:
  host: http://chomik-gateway:17000
