spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-jyoibej2wl1zryew.mdb.yandexcloud.net:6432/chomik 
    username: chomik
    password: 12345678

server:
  port: 17004

payment:
  mock:
    url: http://localhost:17006

chomik:
  order:
    url: http://localhost:17003

balancer:
  host: http://localhost:17004
